import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export const getStaticProps = async () => {
  const data = await fetch(
    `${process.env.API_URL_POKEMON}?limit=20&offset=0`,
  ).then((response) => response.json());

  return {
    props: {
      pokemons: data,
    },
  };
};

export default function Home({ pokemons }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Prueba - OCC - Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Lista de pokemons</h1>
        <ul>
          {pokemons?.results?.map((pokemon, index) => (
            <li key={index}>
              <Link href={`/pokemon/${pokemon.name}`}>
                <a>{pokemon.name}</a>
              </Link>
            </li>
          ))}
        </ul>
      </main>
    </div>
  );
}
